blueprint:
  name: Heater boot management
  description: Wait after the boot because of lot of MQTT messages are coming from climate valves after a HA reboot
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/heater_boot_management.yaml
  input:
    trigging_timer:
      name: Timer to trigger event
      description: Global timer used to wait all TRV MQTT message are sent
      selector:
        entity:
          domain: timer
    switch_automation:
      name: Switching manual/auto/setpoint automation
      description: The automation in charge of switching mode. By default it's called "Room heating mode switching"
      selector:
        entity:
          domain: automation
          multiple: true

mode: queued
max_exceeded: silent

trigger:
- platform: homeassistant
  event: start
  id: TriggeredByBoot

- platform: state
  entity_id: !input trigging_timer
  id: TriggeredByTimer

action:
- choose:
  ### Started by the boot
  - conditions:
    - condition: trigger
      id: TriggeredByBoot
    sequence:
      - service: timer.start
        data: {}
        target:
          entity_id: !input trigging_timer

  ### Started by timer active
  - conditions:
    - condition: trigger
      id:
        - TriggeredByTimer
    - condition: state
      entity_id: !input trigging_timer
      state: active
    sequence:
    - service: automation.turn_off
      data:
        stop_actions: true
      target:
        entity_id: !input switch_automation
      
  ### Started by timer idle
  - conditions:
    - condition: trigger
      id:
        - TriggeredByTimer
    - condition: state
      entity_id: !input trigging_timer
      state: idle
    sequence:
    - service: automation.turn_on
      data: {}
      target:
        entity_id: !input switch_automation
