blueprint:
  name: Room heating request compute
  description: Compute heating requested based on current T° and setpoint °C, and fake climate calibration to force valve
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/heater_request_compute.yaml
  input:
    climate_valve_calibration:
      name: Climate valve calibration
      description: Room TRV calibration/offset value
      selector:
        entity:
          domain: number
    selected_temp:
      name: Selected T° setpoint storage
      description: Helper to store room setpoint calculated by Heating Management
      selector:
        entity:
          domain: input_number
    current_temp:
      name: Current T°
      description: Room T° sensor
      selector:
        entity:
          domain: sensor
    request_heater:
      name: Request heater switch
      description: Room helper for triggering heating system (boiler)
      selector:
        entity:
          domain: input_boolean
    room_link_select:
      name: Room link status
      description: The way the room is connected to environment. Inside, Outside, Both or None.
      selector:
        entity:
          domain: input_select
    active_boolean:
      name: Active for automation
      description: Room activation status
      selector:
        entity:
          domain: input_boolean
    winter_mode_boolean:
      name: Winter switch
      description: Global switch to say it's winter or not.
      selector:
        entity:
          domain: input_boolean

mode: single
max_exceeded: silent

variables:
  local_current_temp: !input current_temp
  local_selected_temp: !input selected_temp

trigger:
- platform: state
  entity_id: !input current_temp
- platform: state
  entity_id: !input selected_temp
- platform: state
  entity_id: !input room_link_select

condition:
  - condition: state
    entity_id: !input winter_mode_boolean
    state: 'on'
  - condition: state
    entity_id: !input active_boolean
    state: 'on'
  - or:
      - condition: state
        entity_id: !input room_link_select
        state: 'Inside'
      - condition: state
        entity_id: !input room_link_select
        state: 'None'

action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ states(local_current_temp)|float < states(local_selected_temp) |float }}'
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: !input request_heater
    - service: number.set_value
      data:
        value: -2.5
      target:
        entity_id: !input climate_valve_calibration 
  - conditions:
    - condition: template
      value_template: '{{ states(local_current_temp)|float >= states(local_selected_temp) |float }}'
    sequence:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: !input request_heater
    - service: number.set_value
      data:
        value: 0
      target:
        entity_id: !input climate_valve_calibration 
