blueprint:
  name: Heating system should start
  description: Heating system should start because at least one room need heating
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/heater_one_need.yaml
  input:
    request_heater:
      name: Request heater switch
      selector:
        entity:
          domain: input_boolean
          multiple: true
    heater_switch:
      name: Heater switch
      selector:
        entity:
          domain: switch
    winter_mode_boolean:
      name: Winter switch
      selector:
        entity:
          domain: input_boolean

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input request_heater
- platform: state
  entity_id: !input winter_mode_boolean

# condition:
#   - condition: state
#     entity_id: !input winter_mode_boolean
#     state: 'on'

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input winter_mode_boolean
      state: 'off'
    sequence:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: !input heater_switch
  - conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: !input request_heater
        state: 'off'
    sequence:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: !input heater_switch
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input request_heater
        state: 'off'
    sequence:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: !input heater_switch
