blueprint:
  name: Room heating mode switching
  description: React to manual or automatic setup on thermostatic valve
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/heater_switch_mode.yaml
  input:
    climate_valve:
      name: Climate valve
      selector:
        entity:
          domain: climate
    manual_boolean:
      name: Manual mode switch
      selector:
        entity:
          domain: input_boolean
    computing_boolean:
      name: Currently computing setpoint
      selector:
        entity:
          domain: input_boolean
    selected_temp:
      name: Selected 째C setpoint
      selector:
        entity:
          domain: input_number
    winter_mode_boolean:
      name: Winter switch
      selector:
        entity:
          domain: input_boolean
    selector_timer:
      name: Timer to trigger read the temp event
      selector:
        entity:
          domain: timer

mode: queued
max_exceeded: silent

variables:
  local_climate_valve: !input climate_valve

trigger:
- platform: state
  entity_id: !input selector_timer
  to: idle
  id: TriggeredByTimer
- platform: state
  entity_id: !input climate_valve
  attribute: temperature
- platform: state
  entity_id: !input climate_valve
  attribute: preset_mode
  to: auto

condition:
  - condition: state
    entity_id: !input winter_mode_boolean
    state: 'on'
  # - condition: state
  #   entity_id: !input computing_boolean
  #   state: 'off'


action:
- choose:

  #### When manual change, wait timer to collect selected T째
  - conditions:
    - condition: not
      conditions:
        - condition: trigger
          id:
            - TriggeredByTimer
    sequence:
      - service: timer.start
        data:
          duration: '0:00:03'
        target:
          entity_id: !input selector_timer

  #### When timer is Ok, it's time to collect selected T째
  - conditions:
    - condition: trigger
      id:
        - TriggeredByTimer
    - condition: state
      entity_id: !input climate_valve
      attribute: preset_mode
      state: manual
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: !input manual_boolean
    - service: input_number.set_value
      data_template:
        value: "{% set temp = state_attr(local_climate_valve,'temperature')|float %}{{ temp }}"
        entity_id: !input selected_temp

  #### When auto mode selected, compute T째
  - conditions:
    - condition: trigger
      id:
        - TriggeredByTimer
    - condition: state
      entity_id: !input climate_valve
      attribute: preset_mode
      state: auto
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: manual
      target:
        entity_id: !input climate_valve
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: !input manual_boolean
