blueprint:
  name: Heating system operationnal or not
  description: Heating system must be set on or off depending on winter mode switch
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/heater_start_stop.yaml
  input:
    climate_valve:
      name: Climate valve
      selector:
        entity:
          domain: climate
          multiple: true
    valve_child_lock:
      name: Valve child lock
      selector:
        entity:
          domain: lock
          multiple: true
    winter_mode_boolean:
      name: Winter switch
      selector:
        entity:
          domain: input_boolean
    setpoint_automation:
      name: Setpoint compute automation
      selector:
        entity:
          domain: automation
          multiple: true
    request_automation:
      name: Request evaluate automation
      selector:
        entity:
          domain: automation
          multiple: true

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input winter_mode_boolean

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input winter_mode_boolean
      state: 'on'
    sequence:
    - service: lock.unlock
      data: {}
      target:
        entity_id: !input valve_child_lock
    - service: climate.turn_on
      data: {}
      target:
        entity_id: !input climate_valve
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - service: automation.trigger
      data: {}
      target:
        entity_id: !input setpoint_automation
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - service: automation.trigger
      data: {}
      target:
        entity_id: !input request_automation

  - conditions:
    - condition: state
      entity_id: !input winter_mode_boolean
      state: 'off'
    sequence:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: !input climate_valve
    - service: lock.lock
      data: {}
      target:
        entity_id: !input valve_child_lock
