blueprint:
  name: Light control
  description: Control light using daylight, occupancy and switch
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/light_control.yaml
  input:
    motion_sensor:
      name: Motion sensor of the room
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_device:
      name: Light management device
      selector:
        entity:
          domain: light
    is_window:
      name: Is there a window in the room
      description: Is there a window, allowing external light to enter ?
      default: True
      selector:
        boolean:

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input motion_sensor
# - platform: state
#   entity_id: !input light_device

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'off'
    sequence:
    - service: light.turn_off
      target: !input light_device
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    sequence:
    - service: light.turn_on
      target: !input light_device
