blueprint:
  name: Light control
  description: Control light using daylight, occupancy and switch
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/light_control.yaml
  input:
    motion_sensor:
      name: Motion sensor of the room
      selector:
        entity:
          domain: binary_sensor
    light_device:
      name: Light management device
      selector:
        entity:
          domain: light

mode: single
max_exceeded: silent

trigger:
- platform: device
  entity_id: !input motion_sensor
- platform: device
  entity_id: !input light_device

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'is_no_motion'
    sequence:
    - service: light.turn_off
      data: {}
      target:
        entity_id: !input light_device
