blueprint:
  name: Light control
  description: Control light based on daylight, cloud covering, occupancy and switch
  domain: automation
  source_url: https://github.com/francois09/HA_blueprints/light_control.yaml
  input:
    motion_sensor:
      name: Motion sensor of the room
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_device:
      name: Light management device
      selector:
        entity:
          domain: light
    is_window:
      name: Is there a window in the room
      description: Is there a window, allowing external light to enter ?
      default: True
      selector:
        boolean:
    is_bedroom:
      name: Is this a bedroom
      description: Is the room a sleeping room ?
      default: False
      selector:
        boolean:
    day_brightness:
      name: Daylight brightness percent
      description: Brightness to set when daylight or blind room
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    night_brightness:
      name: Night brightness percent
      description: Brightness to set when it's night
      default: 2
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1

mode: single
max_exceeded: silent

variables:
  is_window: !input is_window
  is_bedroom: !input is_bedroom
  day_brightness: !input day_brightness
  night_brightness: !input night_brightness

#
# The light must follow these rules:
#
#     - Sunrise-60:
#       - bedroom -> Set night mode off
#  *  - Press switch when light is off:
#  *<   - before sunset+2:00 after sunrise-1:00 (day): -> Turn on
#  *<   - after sunset+2:00 before sunrise-1:00 (night): -> Turn on N%
#     - Press switch when light is on:
#       - before 22h -> Turn off / Set manual mode on
#       - after 22h -> Turn off / Set night mode on
#  *  - No motion detected:
#         - Turn off
#         - Set manual mode off
#     - Motion detected: (if light is off...)
#  *<   - before sunset+2:00 after sunrise-1:00 (day):
#  *<     - no window -> Turn on
#  *<     - window
#           - cloud cover > 60% -> Turn on
#  *<   - after sunset+2:00 before 22h (evening):
#  *      - Turn on N%
#       - after 22h before sunrise-1:00 (night):
#         - not bedroom -> Turn on N%
#         - bedroom:
#           - nigth mode off -> Turn on N%
#
# But steps by steps. For now, actions are:
# - Turn off when no motion detected
# - Turn on 100% when motion, daytime, and no window
# - Turn on N% when motion, nighttime


trigger:
- platform: state
  entity_id: !input motion_sensor
  id: trigger_by_motion
- platform: state
  entity_id: !input light_device
  id: trigger_by_light

action:
- choose:

  ############## MANUAL BUTTON NOT TAKEN INTO ACCOUNT NOW
  # #
  # # Light on (before sunset, after sunrise == Day)
  # # -> Turn on the light
  # - conditions:
  #   - condition: state
  #     entity_id: !input light_device
  #     state: 'on'
  #   - condition: trigger
  #     id:
  #       - trigger_by_light
  #   - condition: sun
  #     before: sunset
  #     after: sunrise
  #     # after_offset: '-1:00:00'
  #     # before_offset: '-1:00:00'
  #   sequence:
  #   - service: light.turn_on
  #     target:
  #       entity_id: !input light_device
  #     data:
  #       brightness_pct: "{{ day_brightness}}"

  ############## MANUAL BUTTON NOT TAKEN INTO ACCOUNT NOW
  # #
  # # Light on (after sunset, before sunrise == Night)
  # # -> Turn on the light at N%
  # - conditions:
  #   - condition: state
  #     entity_id: !input light_device
  #     state: 'on'
  #   - condition: trigger
  #     id:
  #       - trigger_by_light
  #   - condition: sun
  #     before: sunrise
  #     after: sunset
  #     # after_offset: '-1:00:00'
  #     # before_offset: '-1:00:00'
  #   sequence:
  #   - service: light.turn_on
  #     target:
  #       entity_id: !input light_device
  #     data:
  #       brightness_pct: "{{ night_brightness}}"

  #
  # No motion
  # -> Turn off the light
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'off'
    - condition: trigger
      id:
        - trigger_by_motion
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_device

  #
  # Motion during the day, and for no_window rooms
  # -> Turn on the light 100%
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    - condition: trigger
      id:
        - trigger_by_motion
    - condition: state
      entity_id: !input light_device
      state: 'off'
    - condition: sun
      before: sunset
      after: sunrise
      # after_offset: '-1:00:00'
      # before_offset: '-1:00:00'
    - condition: template
      value_template: "{{ not is_window }}"
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_device
      data:
        brightness_pct: "{{ day_brightness}}"
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0

  #
  # Motion during the night, and not a bedroom
  # -> Turn on the light 100% if before 22h
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    - condition: trigger
      id:
        - trigger_by_motion
    - condition: state
      entity_id: !input light_device
      state: 'off'
    - condition: sun
      before: sunrise
      after: sunset
      # after_offset: '-1:00:00'
      # before_offset: '-1:00:00'
    - condition: time
      before: '22:00:00'
    - condition: template
      value_template: "{{ not is_bedroom }}"
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_device
      data:
        brightness_pct: "{{ day_brightness}}"
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0

  #
  # Motion during the night, and not a bedroom
  # -> Turn on the light N% if after 22h
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    - condition: trigger
      id:
        - trigger_by_motion
    - condition: state
      entity_id: !input light_device
      state: 'off'
    - condition: sun
      before: sunrise
      after: sunset
      # after_offset: '-1:00:00'
      # before_offset: '-1:00:00'
    - condition: time
      after: '22:00:00'
    - condition: template
      value_template: "{{ not is_bedroom }}"
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_device
      data:
        brightness_pct: "{{ night_brightness}}"
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
